language: node_js

node_js:
  - '8'

notifications:
  email: false

cache:
  directories:
    - "node_modules"

before_install:
  - sudo apt-get update #Puppeteer starts to glitch out if we don't update packages...for some reason.

script:
  - npm run build
  - npm run test --silent

deploy:
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    skip_cleanup: true #make sure we keep our dist folder
    on:
      tags: true

#  - provider: releases
#    api_key: $GITHUB_TOKEN
#    file: 
#      - "dist/salieo.js"
#      - "dist/salieo.min.js"
#    skip_cleanup: true #make sure we keep our dist folder
#    on:
#      tags: true
